In [30]:

import pandas as pd 
import numpy as np

In [209]:
combinedFile = '/Users/swethakolalapudi/Desktop/Reg_Data/PricesHistorical3.csv'

data=pd.read_csv(combinedFile ,sep=",")
data.head()

,Date,AAPL,GOOG,VLO,CVX,XOM,GSPC,FVX
0,03/01/2017,121.950000,823.310000,67.310000,113.790000,85.510000,2294.690000,1.941
1,01/12/2016,115.320023,771.820007,67.611183,116.584061,89.442131,2238.830078,1.934
2,01/11/2016,110.042900,758.039978,60.921318,110.502274,86.508957,2198.810059,1.834
3,03/10/2016,112.472404,784.539978,58.081470,102.728424,81.840340,2126.149902,1.313
4,01/09/2016,111.987015,777.289978,51.963501,100.933739,85.730011,2168.270020,1.156

In [210]:
data['Date'] = pd.to_datetime(data['Date'], format='%d/%m/%Y')
data.head()

,Date,AAPL,GOOG,VLO,CVX,XOM,GSPC,FVX
0,2017-01-03,121.950000,823.310000,67.310000,113.790000,85.510000,2294.690000,1.941
1,2016-12-01,115.320023,771.820007,67.611183,116.584061,89.442131,2238.830078,1.934
2,2016-11-01,110.042900,758.039978,60.921318,110.502274,86.508957,2198.810059,1.834
3,2016-10-03,112.472404,784.539978,58.081470,102.728424,81.840340,2126.149902,1.313
4,2016-09-01,111.987015,777.289978,51.963501,100.933739,85.730011,2168.270020,1.156

In [211]:
data = data.sort_values(['Date'], ascending=[True])
data.head()

,Date,AAPL,GOOG,VLO,CVX,XOM,GSPC,FVX
120,2007-01-03,11.107141,250.499939,39.694862,50.777351,56.765919,1438.239990,4.819
119,2007-02-01,10.962033,224.500885,42.169876,48.082939,55.145882,1406.819946,4.503
118,2007-03-01,12.037377,228.851547,47.263386,51.900383,58.046268,1420.859985,4.537
117,2007-04-02,12.930043,235.454956,51.470112,54.588032,61.069752,1482.369995,4.516
116,2007-05-01,15.701322,248.706726,54.776485,57.598267,64.261772,1530.619995,4.853

In [212]:
returns = data[[key for key in dict(data.dtypes) if dict(data.dtypes)[key] in ['float64', 'int64']]].pct_change()
returns = data[["AAPL","GOOG","XOM","CVX","VLO","GSPC","FVX"]].pct_change()

In [213]:
returns.head()

         AAPL      GOOG       XOM       CVX       VLO      GSPC       FVX
120       NaN       NaN       NaN       NaN       NaN       NaN       NaN
119 -0.013064 -0.103789 -0.028539 -0.053063  0.062351 -0.021846 -0.065574
118  0.098097  0.019379  0.052595  0.079393  0.120786  0.009980  0.007551
117  0.074158  0.028855  0.052087  0.051785  0.089006  0.043291 -0.004629
116  0.214329  0.056282  0.052268  0.055145  0.064239  0.032549  0.074624

In [214]:
returns = returns[1:]

In [215]:
yVars = returns[["GOOG","XOM","CVX","VLO","GSPC","FVX"]]

In [216]:
stdYVars = (yVars - yVars .mean()) / (yVars .std())

In [217]:
yVars .cov()
yVars .corr()

          GOOG       XOM       CVX       VLO      GSPC       FVX
GOOG  1.000000  0.296639  0.358988  0.397233  0.566361  0.247775
XOM   0.296639  1.000000  0.794910  0.343255  0.549284  0.190377
CVX   0.358988  0.794910  1.000000  0.401616  0.643503  0.236250
VLO   0.397233  0.343255  0.401616  1.000000  0.585980  0.290939
GSPC  0.566361  0.549284  0.643503  0.585980  1.000000  0.271478
FVX   0.247775  0.190377  0.236250  0.290939  0.271478  1.000000

In [218]:
eig_val, eig_vec = np.linalg.eig(stdYVars.cov())

In [219]:
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(len(eig_val))]

In [220]:
eig_pairs.sort(key=lambda x: x[0], reverse=True)

In [221]:
eig_pairs

[(3.1459527934123352,
  array([-0.36888058, -0.43483546, -0.46995619, -0.39270158, -0.48817562,
         -0.24790412])),
 (0.97887501264048482,
  array([-0.33713512,  0.49740615,  0.40786685, -0.30141047, -0.02499783,
         -0.61733176])),
 (0.78520516166320942,
  array([-0.49720335,  0.25617574,  0.20001077, -0.2357954 , -0.22831947,
          0.73445848])),
 (0.59531868678877364,
  array([-0.62527658, -0.06762299, -0.05873725,  0.76388678,  0.03893528,
         -0.12636179])),
 (0.30347275530593398,
  array([-0.33190136, -0.35822719,  0.01880332, -0.33681084,  0.80396233,
          0.03693549])),
 (0.19117559018926478,
  array([ 0.04389248, -0.60413545,  0.75430622,  0.04871521, -0.24710021,
         -0.02615804]))]

In [222]:
eVector1 = eig_vec[:,0]
eVector2 = eig_vec[:,1]
eVector3 = eig_vec[:,2]

In [223]:
pca1 = np.dot(stdYVars,eVector1.T).T
pca1

array([ 1.53322382, -1.50234213, -1.55256284, -1.62395966, -0.09663583,
        0.93823144, -0.27957545, -1.76541527, -0.90111747,  1.92923911,
       -0.89940503,  4.27199975,  1.06393377,  1.56796362, -3.89748445,
       -0.21594336,  2.44982842,  3.51800973, -0.07280383,  3.01245524,
        5.02883861,  1.42701908,  0.18607333,  0.77354152,  4.09781747,
       -1.1351224 , -1.77894402, -1.89842092,  0.93143237, -1.45166034,
       -0.40378792, -0.51508386, -0.74121007, -0.83968222, -0.00657368,
        2.17555611, -0.05155364, -2.04455783, -0.38566707,  3.70633122,
        2.77196112, -1.91425566,  1.79329853, -2.93979734, -1.6982203 ,
       -0.41233337, -3.54633664, -1.61470643, -2.16693848,  0.05409101,
        0.06988946,  1.56911567,  1.23499044,  0.16911815,  3.1461962 ,
        2.71277462, -4.82895256,  0.46055438, -0.53776002,  0.31895367,
       -1.8388621 , -0.63698897,  1.20522854,  3.24608238, -2.23642738,
       -0.93140947, -1.19001369, -1.34642586,  1.44909472,  0.44738976,
       -0.39405613, -2.85298548, -0.30036796, -0.25816112,  0.40583928,
       -1.85025645,  0.68526788, -1.28815003,  1.4431819 ,  0.19441268,
       -1.9501846 , -1.3552473 , -2.00957243,  2.27315088, -0.95894618,
       -0.45908801, -0.68639441,  0.17508331, -0.30355719,  0.50958836,
       -0.4785186 ,  1.89380799, -0.30194338,  1.52014117, -0.22319895,
        1.948621  , -2.20941621,  1.06712051, -0.16152032,  0.64834448,
        0.92931581,  0.14670458,  2.32744035,  1.07589898, -4.18868538,
       -0.52331133,  0.85766745,  1.78148573,  0.92457491, -2.55276433,
       -0.33537303, -0.19392515,  0.38841751, -0.08959686, -0.02555021,
        0.20712704,  0.06826373, -1.92936895, -1.25795347,  0.30534225])

In [224]:
pca2 = np.dot(stdYVars,eVector2.T).T

In [225]:
pca3 = np.dot(stdYVars,eVector3.T).T

In [226]:
xData = np.vstack([pca1,pca2,pca3]).T
xData

array([[ 1.53322382, -0.15235316, -0.00597316],
       [-1.50234213,  0.64944468,  0.22240361],
       [-1.55256284,  0.53486609, -0.09269946],
       [-1.62395966,  0.19897512,  0.25387167],
       [-0.09663583,  0.08380966,  0.12138663],
       [ 0.93823144,  0.88625416,  0.36105683],
       [-0.27957545,  0.55970201, -0.3110369 ],
       [-1.76541527,  0.9469021 , -0.04799421],
       [-0.90111747, -1.30000175, -1.76595244],
       [ 1.92923911,  0.51633915, -0.57910702],
       [-0.89940503,  0.72883603,  0.49655574],
       [ 4.27199975,  0.29691939,  0.08286062],
       [ 1.06393377,  1.73577946,  0.98328888],
       [ 1.56796362,  0.34264528,  0.51586391],
       [-3.89748445, -0.24374951,  0.12102469],
       [-0.21594336, -0.90785422,  0.2895987 ],
       [ 2.44982842,  0.97985397,  1.38296334],
       [ 3.51800973, -0.92771328,  0.02659779],
       [-0.07280383,  0.36656226, -0.14165991],
       [ 3.01245524,  0.46266179,  1.13567114],
       [ 5.02883861,  0.47602746,  1.39818446],
       [ 1.42701908,  3.74044769,  0.95260233],
       [ 0.18607333, -0.36532811, -1.89677245],
       [ 0.77354152, -2.30412657,  0.28268523],
       [ 4.09781747, -1.78177871,  0.40124027],
       [-1.1351224 ,  1.51241246, -0.84890348],
       [-1.77894402, -2.09614576, -0.65473228],
       [-1.89842092, -0.68315984,  0.28586486],
       [ 0.93143237,  0.30451592,  0.99049985],
       [-1.45166034,  0.01133805, -0.61615806],
       [-0.40378792, -0.10942338, -0.75573607],
       [-0.51508386, -0.33349048, -0.80805184],
       [-0.74121007,  0.92841093,  0.36968725],
       [-0.83968222,  1.25308344, -0.78325729],
       [-0.00657368, -2.88526352,  0.58110564],
       [ 2.17555611, -0.18687891, -0.23816164],
       [-0.05155364,  0.48803551,  0.03836007],
       [-2.04455783, -0.53054478, -0.04802932],
       [-0.38566707,  0.98476955,  0.34220151],
       [ 3.70633122, -0.49736893, -0.3468563 ],
       [ 2.77196112, -0.1031157 , -0.37208676],
       [-1.91425566,  1.53318814, -0.57912783],
       [ 1.79329853,  1.00186211,  0.01900811],
       [-2.93979734,  0.27730398, -1.28905215],
       [-1.6982203 ,  0.49752609, -1.08701799],
       [-0.41233337, -0.38146117,  1.87142004],
       [-3.54633664, -0.96970456,  1.45890859],
       [-1.61470643,  1.17582022,  0.21412063],
       [-2.16693848,  0.57991938,  0.68334159],
       [ 0.05409101, -0.08907952,  0.42787587],
       [ 0.06988946,  1.4843383 ,  0.21573331],
       [ 1.56911567,  0.05887485, -0.72748021],
       [ 1.23499044, -0.19365502,  0.54593983],
       [ 0.16911815,  0.04399089, -2.06326572],
       [ 3.1461962 ,  0.96621848, -0.83367356],
       [ 2.71277462,  0.1376908 ,  0.93606399],
       [-4.82895256, -0.20870589, -1.12715293],
       [ 0.46055438,  0.72955952,  0.07813933],
       [-0.53776002,  1.16619637, -0.54168367],
       [ 0.31895367,  0.23667096, -0.73861296],
       [-1.8388621 , -0.44973553,  0.96289104],
       [-0.63698897, -1.20234789,  0.45538377],
       [ 1.20522854,  1.1644492 , -0.60906983],
       [ 3.24608238, -0.07582194, -0.612012  ],
       [-2.23642738,  0.66224688,  0.70082433],
       [-0.93140947,  0.39116374, -1.50926169],
       [-1.19001369, -0.38554543, -0.69832242],
       [-1.34642586,  0.0758261 , -0.02551641],
       [ 1.44909472, -0.33605474,  1.38007364],
       [ 0.44738976, -0.37390289, -1.31681428],
       [-0.39405613, -0.99913188,  0.68266776],
       [-2.85298548, -1.11092197,  0.26691181],
       [-0.30036796,  0.32758629, -0.98580883],
       [-0.25816112,  0.17797015,  0.01095639],
       [ 0.40583928,  0.68355928, -0.57104933],
       [-1.85025645, -2.4703744 ,  2.26203134],
       [ 0.68526788, -1.19832646,  1.79951936],
       [-1.28815003,  0.67365549,  0.13325169],
       [ 1.4431819 , -1.34849537,  0.76191105],
       [ 0.19441268,  0.41676978, -0.90552854],
       [-1.9501846 , -0.74413888, -1.73991897],
       [-1.3552473 ,  0.11299719,  0.06016767],
       [-2.00957243, -0.66520334,  1.25459078],
       [ 2.27315088, -1.36836752, -1.62294034],
       [-0.95894618,  0.84893647,  0.21461649],
       [-0.45908801, -0.20669959,  1.18110771],
       [-0.68639441,  1.0145138 ,  0.49150464],
       [ 0.17508331, -0.07461046, -0.94686215],
       [-0.30355719,  0.3575308 ,  0.55983223],
       [ 0.50958836, -0.61482823,  0.42976195],
       [-0.4785186 ,  0.28731387, -0.56509699],
       [ 1.89380799, -1.13837   ,  0.28789798],
       [-0.30194338,  0.59958983, -0.33982136],
       [ 1.52014117, -0.75771721, -0.73969106],
       [-0.22319895,  0.10634379,  0.88662535],
       [ 1.948621  , -0.25721107, -1.9897923 ],
       [-2.20941621, -1.23946867,  0.72112115],
       [ 1.06712051, -0.19091494, -0.50533829],
       [-0.16152032,  0.85593182,  0.94633264],
       [ 0.64834448, -0.79610945, -0.26535942],
       [ 0.92931581, -1.20493438,  0.36545882],
       [ 0.14670458, -1.86363413, -2.14455731],
       [ 2.32744035, -0.58498797,  0.16309408],
       [ 1.07589898,  0.17215279, -0.4187924 ],
       [-4.18868538,  0.79311979,  0.09733313],
       [-0.52331133, -0.72856125,  0.01349409],
       [ 0.85766745, -0.88654937,  0.06110908],
       [ 1.78148573,  0.92414011, -0.78274092],
       [ 0.92457491,  1.14466604,  0.38567596],
       [-2.55276433,  0.92795303, -0.09491177],
       [-0.33537303,  1.41829383,  1.41218883],
       [-0.19392515, -0.19532257,  0.13216005],
       [ 0.38841751,  2.2968167 , -0.2807862 ],
       [-0.08959686, -1.33189545, -1.08805152],
       [-0.02555021, -0.96364771,  0.52610267],
       [ 0.20712704,  0.3185219 ,  0.0655447 ],
       [ 0.06826373, -1.28034815,  0.32210132],
       [-1.92936895, -0.5282733 ,  2.48407987],
       [-1.25795347,  0.1199804 ,  0.25563934],
       [ 0.30534225, -0.92642639, -0.7618091 ]])

In [227]:
stdReturns = (returns["AAPL"] - returns["AAPL"].mean()) / (returns["AAPL"].std())

In [228]:
yData = (returns["AAPL"] - returns["AAPL"].mean()) / (returns["AAPL"].std())

In [229]:
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

In [230]:
goodAaplModel = linear_model.LinearRegression()

In [231]:
goodAaplModel .fit(xData,yData)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [232]:
goodAaplModel .score(xData,yData)

0.37007268576699703

In [233]:
model = sm.OLS(yData, xData)

In [202]:
results = model.fit()

In [203]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   AAPL   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.354
Method:                 Least Squares   F-statistic:                     22.91
Date:                Sun, 26 Feb 2017   Prob (F-statistic):           9.72e-12
Time:                        07:18:02   Log-Likelihood:                -142.04
No. Observations:                 120   AIC:                             290.1
Df Residuals:                     117   BIC:                             298.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
x1            -0.3069      0.041     -7.419      0.000        -0.389    -0.225
x2            -0.1005      0.074     -1.355      0.178        -0.247     0.046
x3            -0.2852      0.083     -3.444      0.001        -0.449    -0.121
==============================================================================
Omnibus:                       14.787   Durbin-Watson:                   1.684
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.788
Skew:                          -0.660   Prob(JB):                     5.05e-05
Kurtosis:                       4.489   Cond. No.                         2.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.